branches:
  except:
    - /travis/
skip_tags: true

cache:
  - C:\strawberry

install:
  - if not exist "C:\strawberry" choco install strawberryperl --version 5.26.1.1
  - set ST=C:\strawberry
  - set PATH=%ST%\perl\bin;%ST%\perl\site\bin;%ST%\c\bin;%PATH%
# we're in C:\projects\geo-gdal-2-02
#  - dir
#  - dir c:\
#  - dir c:\projects
  #  ensure we have some packages that aren't picked up by the install system
  - cpanm --quiet --notest Alien::Build
  - cpanm --quiet --notest HTML::LinkExtor
  - cpanm --quiet --notest Test::CChecker
  - cpanm --quiet --notest Alien::MSYS
  - cpanm --quiet --notest Alien::patch
  - cpanm --quiet --notest Data::Dumper
  # install alien gdal
  - svn co https://github.com/shawnlaffan/perl-alien-gdal.git/trunk alien-gdal
  - cd alien-gdal
  - SET FORCE_DYNAMIC=1
  - dir c:\strawberry\perl\bin
  - dir c:\strawberry\perl\lib
  - perl Makefile.PL
  - gmake | perl -ane "$|=1;print '.'"
  - gmake install
  - cd ..
  - rd /s /q alien-gdal
  - gcc -v

build_script:
  - perl Makefile.PL
  - gmake
  - gmake test
  #- prove -l

