branches:
  except:
    - /travis/
skip_tags: true

cache:
  - C:\strawberry

install:
  - if not exist "C:\strawberry" choco install strawberryperl --version 5.26.1.1
  - set ST=C:\strawberry
  - set PATH=%ST%\perl\bin;%ST%\perl\site\bin;%ST%\c\bin;%PATH%
  - dir
  - dir c:\
  - dir c:\projects
  - cd Geo-GDAL-2.02
  #  ensure we have some packages that aren't picked up by the install system
  - cpanm --quiet Alien::Build
  - cpanm --quiet HTML::LinkExtor
  - cpanm --quiet Test::CChecker
  - cpanm --quiet Alien::MSYS
  - svn co https://github.com/ajolma/perl-alien-gdal.git/trunk alien-gdal; cd alien-gdal; perl Makefile.PL; gmake | perl -ane '$|=1;print "."'; gmake install; cd ..; rd /s /q alien-gdal
  - gcc -v

build_script:
  - perl Makefile.PL
  - gmake
  #- prove -l

